version: '3.8'
services:
  frontend:
    container_name: frontend_container
    image: frontend_image
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules