import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "FMovies",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-f-gray text-white flex flex-col min-h-screen relative max-w-[1920px] mx-auto`}>
                <div>
                    {children}
                </div>
            </body>
        </html>
    );
}